global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'commerce-api'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:18080']

  - job_name: 'order-api'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:18081']

  - job_name: 'like-api'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:18083']