server:
  shutdown: graceful
  tomcat:
    threads:
      max: 200 # 최대 워커 스레드 수 (default : 200)
      min-spare: 10 # 최소 유지 스레드 수 (default : 10)
    connection-timeout: 1m # 연결 타임아웃 (ms) (default : 60000ms = 1m)
    max-connections: 8192 # 최대 동시 연결 수 (default : 8192)
    accept-count: 100 # 대기 큐 크기 (default : 100)
    keep-alive-timeout: 60s # 60s
  max-http-request-header-size: 8KB

spring:
  main:
    web-application-type: servlet
  application:
    name: commerce-api
  profiles:
    active: local
  config:
    import:
      - jpa.yml
      - logging.yml
      - redis.yml
      - feign.yml
      - kafka.yml
      - monitoring.yml
  datasource:
    hikari:
      connection-timeout: 3000       # 커넥션 풀에서 커넥션 얻는 최대 대기 시간
      validation-timeout: 2000       # 커넥션 유효성 검사 제한 시간


logging:
  level:
    io.github.resilience4j.retry: DEBUG
    # Tx 경계/합류/롤백/서스펜드
    org.springframework.transaction.interceptor: TRACE
    org.springframework.orm.jpa.JpaTransactionManager: DEBUG
    org.springframework.jdbc.datasource.DataSourceTransactionManager: DEBUG   # NESTED 쓸 때

    # SQL + 바인딩 값 (Hibernate 6)
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

springdoc:
  use-fqn: true
  swagger-ui:
    path: /swagger-ui.html

---
spring:
  config:
    activate:
      on-profile: local, test

---
spring:
  config:
    activate:
      on-profile: dev

---
spring:
  config:
    activate:
      on-profile: qa

---
spring:
  config:
    activate:
      on-profile: prd

springdoc:
  api-docs:
    enabled: false
